baseURL = "https://barpilot.io/"
languageCode = "en-us"
title = "barpilot"

theme = "hugo-elate-theme"

[params]

# Meta
author = "Guilhem Lettron"
description = "barpilot website"
email = "guilhem@barpilot.io"

[params.navigation]
brand = "barpilot"
about = "About"
contact = "Contact"

[params.hero]
title = "A managed kubernetes cluster just for you"
subtitle = "Kubernetes in your infrastucture should not be a problem!"

[[params.intro.item]]
icon = "icon-paper-plane"
title = "Easy"
description = "Creating a cluster should be as easy as a single click"
url = "#"
button = "Get In Touch"

[[params.intro.item]]
title = "Managed"
description = "We are managing installation, configuration and upgrade. Just focus on your business."
icon = "icon-magic-wand"
url = "#"
button = "Get In Touch"

#[[params.intro.item]]
#title = "Scalable"
#icon = "icon-grid"
#description = "Extending your cluster is a single command line to run on your servers."
#url = "#"
#button = "Get In Touch"

[[params.intro.item]]
title = "Secured"
icon = "icon-lock"
description = "Your business, your data. We have no access to your workload or network."
url = "#"
button = "Get In Touch"

# About section
[params.about]
enable = true
title = "About"
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

[[params.about.item]]
name = "Guilhem Lettron"
position = "Founder"
description = "Do epic shit or die trying."
img = "guilhem.jpg"
alt = "Guilhem"
social = [
  ["icon-github", "https://github.com/guilhem"],
  ["icon-twitter", "https://twitter.com/guilhemlettron"],
  ["icon-linkedin", "https://www.linkedin.com/in/guilhemlettron"]
]

# Contact section
[params.contact]
enable = true
form = "Contact Us"
title = "Get in touch"
description = "Interested? just leave us a message"

## Available icons: http://simplelineicons.com/
#details = [
#    ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
#    ["icon-phone", "(123) 465-6789"],
#    ["icon-envelope", "info@freehtml5.co"],
#    ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
#  ]

name = "Name"
email = "Email"
message = "Message"
button = "Send message"

